spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${BANCO:biblioteca_db}
    username: ${BANCO_USER:postgres}
    password: ${BANCO_SENHA:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  docker:
    compose:
      enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:4200"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"